codec_type_list = {
    "MPEG-4 Video": "mp4v",
    "H.264 / AVC": "avc1",
    "H.264 / AVC (Alternative)": "H264",
    "Xvid MPEG-4": "XVID",
    "Motion JPEG": "MJPG",
    "VP9 Video": "vp09",
    "VP8 Video": "VP80",
    "DivX MPEG-4": "DIVX",
    "DivX 3 Low-Motion": "DIV3",
    "H.265 / HEVC": "HEVC",
    "Uncompressed YUV 4:2:0": "I420",
    "MPEG-1 Video": "PIM1",
    "Ogg Theora": "THEO",
    "Windows Media Video 7": "WMV1",
    "Windows Media Video 8": "WMV2",
    "Uncompressed YUV 4:2:2": "YUY2",
}
container_type_list = {
    "MPEG-4 Part 14": ".mp4",
    "Matroska Video": ".mkv",
    "Audio Video Interleave": ".avi",
    "QuickTime Movie": ".mov",
    "WebM Video": ".webm",
    "3GPP Multimedia File": ".3gp",
    "Advanced Systems Format": ".asf",
    "Flash Video": ".flv",
    "MPEG-2 Transport Stream": ".m2ts",
    "iTunes Video File": ".m4v",
    "MPEG Video File": ".mpg",
    "Ogg Video": ".ogv",
    "MPEG Transport Stream": ".ts",
    "Windows Media Video": ".wmv",
}